-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/jayzone91/JayVim/blob/main/lua/jayvim/config/options.lua
-- Add any additional options here
